apiVersion: v1
kind: Service
metadata:
  name: postgres-database
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgres-database
  sessionAffinity: None
  type: ClusterIP
