apiVersion: v1
kind: Service
metadata:
  name: kafka-spammer
  labels:
    app: kafka-spammer    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: kafka-spammer
  type: LoadBalancer    